[book]
authors = ["codermaybe"]
language = "en"
multilingual = false
src = "src"
title = "Xu's Blog"
description = "This blog record my learning progress"
[output.html]
default-theme = "Rust"
git-repository-url = "https://github.com/codermaybe"
git-repository-icon = "fa-github"

[output.html.search]
limit-results = 8

[rust]
edition = "2018"

[build]
build-dir = "book"
